SmartHome/Models/HomeViewModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartHome.Data.Enumerables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartHome.Models
{
    public class HomeViewTableModel{
        public List<HomeViewModel> Items { get; set; }
    }
    public class HomeViewModel {
        public int Id { get; set; }
        public string Name { get; set; }        
        public string Creator { get; set; }   
        public bool IsUserCreator { get; set; }            
        public List<SelectListItem> Actions { get; set; } 
        public List<EndPointsViewModel> EndPoints { get; set; }
    }    
    public class EndPointsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public EndPointStateEnum State { get; set; }
        public EndPointTypeEnum Type { get; set; }                        
    }

    public class AddUserToHomeViewModel
    {
        public int HomeId { get; set; }
        public string Email { get; set; }
    }
    public class AddEndPointToHomeViewModel
    {
        public int HomeId { get; set; }
        public string EndPointMAC { get; set; }
    }

    public class ManageUsersViewModel
    {
        public int HomeId { get; set; }      
        public List<User> Users { get; set; }        
    }
    public class User
    {
        public string Email { get; set; }        
    }
}

SmartHome/Controllers/API/EndPointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class EndPointsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IEndPointService _endPointService;


        public EndPointsController(ApplicationDbContext context, IEndPointService endPointService)
        {
            _endPointService = endPointService;
            _context = context;
        }


        // GET: api/EndPoints1/5
        [HttpGet("{id}")]
        public async Task<ActionResult<EndPoint>> GetEndPoint(int id, string userId)
        {
            var endPoint = _endPointService.GetEndPointById(id,userId);

            if (endPoint == null)
            {
                return NotFound();
            }

            return endPoint;
        }

        // PUT: api/EndPoints1/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutEndPoint(int id, EndPoint endPoint)
        {
            if (id != endPoint.Id)
            {
                return BadRequest();
            }

            _context.Entry(endPoint).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EndPointExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/EndPoints1
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<EndPoint>> PostEndPoint(EndPoint endPoint)
        {
            _endPointService.CreateEndPoint(endPoint);

            return CreatedAtAction("GetEndPoint", new { id = endPoint.Id }, endPoint);
        }

        // DELETE: api/EndPoints1/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<EndPoint>> DeleteEndPoint(int id, string userId)
        {
            var endPoint = _endPointService.GetEndPointById(id, userId);
            if (endPoint == null)
            {
                return NotFound();
            }

            _endPointService.DeleteEndPoint(id, userId);

            return endPoint;
        }

        private bool EndPointExists(int id)
        {
            return _context.EndPoints.Any(e => e.Id == id);
        }
    }
}

SmartHome/Controllers/API/HomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class HomesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHomeService _homeService;

        public HomesController(ApplicationDbContext context, IHomeService homeService)
        {
            _homeService = homeService;
            _context = context;
        }

        // GET: api/Homes/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Home>> GetHome(int id, string userId)
        {
            var home = _homeService.GetHomeById(id, userId);

            if (home == null)
            {
                return NotFound();
            }

            return home;
        }

        // PUT: api/Homes/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutHome(int id, Home home)
        {
            if (id != home.Id)
            {
                return BadRequest();
            }

            _context.Entry(home).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HomeExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Homes
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Home>> PostHome(Home home, string creatorId)
        {
            _homeService.CreateHome(home, creatorId);

            return CreatedAtAction("GetHome", new { id = home.Id }, home);
        }

        // DELETE: api/Homes/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Home>> DeleteHome(int id, string userId)
        {
            var home = _homeService.GetHomeById(id, userId);
            if (home == null)
            {
                return NotFound();
            }

            _homeService.DeleteHome(id, userId);

            return home;
        }

        private bool HomeExists(int id)
        {
            return _context.Homes.Any(e => e.Id == id);
        }
    }
}

SmartHome/Controllers/EndPointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Models;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers
{
    [Authorize]
    public class EndPointsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEndPointService _endPointService;
        private readonly IRuleService _ruleService;

        public EndPointsController(ApplicationDbContext context, IEndPointService endPointService, IRuleService ruleService)
        {
            _context = context;
            _endPointService = endPointService;
            _ruleService = ruleService;
        }

        private string GetLoggedInUserId()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return id;
        }

        public async Task<IActionResult> AddRuleToEndPoint(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            return View(new Rule() { EndPointId = id.Value, RuleType = Data.Enumerables.RuleTypeEnum.TimeBased });
        }
        [HttpPost]
        public async Task<IActionResult> AddRuleToEndPoint([Bind("Name,RuleType,ValueFrom,ValueTo,TimeFrom,TimeTo,EndPointId")]  Rule rule)
        {
            _ruleService.CreateRule(rule, GetLoggedInUserId());
            return RedirectToAction("ManageRulesForEndPoint", new { id = rule.EndPointId });
        }

        public async Task<IActionResult> ManageRulesForEndPoint(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(CastRulesToViewModel(id.Value, _endPointService.GetRulesForEndPoint(id.Value, GetLoggedInUserId()).ToList()));
        }

        private EndPointRulesTableViewModel CastRulesToViewModel(int endPointId, List<Rule> list)
        {
            var isCreator = false;
            var homeId = _endPointService.GetHomeIdForEndPoint(endPointId).Value;
            if (list.Any())
                isCreator = _ruleService.IsUserCreator(list.FirstOrDefault().Id, GetLoggedInUserId());
            var items = list.Select(sl => new EndPointRuleViewModel
            {
                Id = sl.Id,
                Name = sl.Name,
                RuleType = sl.RuleType,
                TimeFrom = sl.TimeFrom,
                TimeTo = sl.TimeTo,
                ValueFrom = sl.ValueFrom,
                ValueTo = sl.ValueTo
            }).ToList();
            return new EndPointRulesTableViewModel
            {
                IsUserCreator = isCreator,
                EndPointId = endPointId,
                HomeId = homeId,
                Items = items
            };
        }

        // GET: EndPoints/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endPoint = _endPointService.GetEndPointById(id.Value, GetLoggedInUserId());
            if (endPoint == null)
            {
                return NotFound();
            }
            return View(endPoint);
        }

        // POST: EndPoints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Type,HomeId")] EndPoint endPoint)
        {
            if (id != endPoint.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _endPointService.UpdateEndPoint(endPoint, GetLoggedInUserId());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EndPointExists(endPoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Homes", new { id = endPoint.HomeId });
            }
            return View(endPoint);
        }

        // GET: EndPoints/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endPoint = _endPointService.GetEndPointById(id.Value, GetLoggedInUserId());
            if (endPoint == null)
            {
                return NotFound();
            }

            return View(endPoint);
        }

        // POST: EndPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var endpoint = _endPointService.GetEndPointById(id, GetLoggedInUserId());
            _endPointService.DeleteEndPoint(id, GetLoggedInUserId());
            return RedirectToAction("Details", "Homes", endpoint.HomeId);
        }

        private bool EndPointExists(int id)
        {
            return _context.EndPoints.Any(e => e.Id == id);
        }
    }
}

SmartHome/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SmartHome.Data.DbModels;
using SmartHome.Models;

namespace SmartHome.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;        
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Homes", null);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SmartHome/Views/Homes/AddEndPointToHome.cshtml
@model SmartHome.Models.AddEndPointToHomeViewModel
@{
    ViewData["Title"] = "AddEndPointToHome";
}

<h1>Add endpoint to home</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEndPointToHome">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="HomeId" class="form-control" type="hidden" />

                <label asp-for="EndPointMAC" class="control-label"></label>
                <input asp-for="EndPointMAC" class="form-control" />
                <span asp-validation-for="EndPointMAC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back", "Details", new { @id = Model.HomeId }, new { @class = "btn btn-light" })
            </div>
        </form>
    </div>
</div>

SmartHome/Views/Homes/AddUserToHome.cshtml
@model SmartHome.Models.AddUserToHomeViewModel
@{
    ViewData["Title"] = "AddUserToHome";
}

<h1>Add user to home</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUserToHome">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="HomeId" class="form-control" type="hidden" />

                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back", "ManageUsersInHome", new { @id = Model.HomeId },new { @class = "btn btn-light" })

            </div>
        </form>
    </div>
</div>

SmartHome/Views/Homes/Create.cshtml
@model SmartHome.Data.DbModels.Home

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Home</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" asp-controller="Home" class="btn btn-light">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartHome/Views/Homes/Delete.cshtml
@model SmartHome.Data.DbModels.Home

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Home</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-light">Back</a>
    </form>
</div>

SmartHome/Views/Homes/Details.cshtml
@model SmartHome.Models.HomeViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Home details - @Html.DisplayFor(model => model.Name)</h1>

@if (Model.IsUserCreator)
{
    <div class="row">
        <input type="hidden" id="homeId" name="homeId" value="@Model.Id" />
        <a asp-action="ManageUsersInHome" asp-route-id="@Model.Id" class="btn-light btn">Manage users in home</a>
        <a asp-action="AddEndPointToHome" asp-route-id="@Model.Id" class="btn-light btn">Add endpoint to home</a>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit home information</a>
    </div>
}

<div class="form-group mt-5">
    @await Html.PartialAsync("_EndPointsTable", Model)
</div>
<div class="row">
    <a asp-action="Index" class="btn btn-light">Back</a>
</div>

SmartHome/Views/Homes/Edit.cshtml
@model SmartHome.Data.DbModels.Home

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Home</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Details" asp-controller="Homes" asp-route-id="@Model.Id" class="btn btn-light">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartHome/Views/Homes/Index.cshtml
@model HomeViewTableModel

@{
    ViewData["Title"] = "Your homes";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>Creator</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Items){
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @item.Creator
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> 
                @if (item.IsUserCreator){
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>

SmartHome/Views/Homes/ManageUsersInHome.cshtml
@model SmartHome.Models.ManageUsersViewModel
@{
    ViewData["Title"] = "ManageUsersInHome";
}
<h1>Manage users in home</h1>

<a asp-action="AddUserToHome" asp-route-id="@Model.HomeId" class="btn-primary btn">Add user to home</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Users)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="DeleteUserFromHome" asp-route-homeId="@Model.HomeId" asp-route-email="@item.Email" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this user from home?')">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.ActionLink("Back", "Details", new { @id = Model.HomeId }, new { @class = "btn btn-light" })

SmartHome/Views/Homes/_EndPointsTable.cshtml
@model SmartHome.Models.HomeViewModel

@if (Model.EndPoints.Any())
{

    <h2>EndPoints</h2>
    <table id="table" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.EndPoints.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndPoints.FirstOrDefault().Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndPoints.FirstOrDefault().Type)
                </th>
                <th>
                    Actions
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.EndPoints)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>                                                
                        <select asp-for="@item.State" asp-items="@Model.Actions" class="custom-select js-endpoint-state" data_id="@item.Id">
                        </select>                        
                    </td>
                    <td>
                        <a asp-action="ManageRulesForEndPoint" asp-route-id="@item.Id" asp-controller="EndPoints" class="btn-light btn">Rules</a>
                        <a asp-action="Edit" asp-controller="EndPoints" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                        @if (Model.IsUserCreator)
                        {
                            <a asp-action="Delete" asp-controller="EndPoints" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h5>There are no endpoints added to this home</h5>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('.js-endpoint-state').change(function () {            
            $.ajax({
                type: "POST",
                url: '/Homes/ChangeEndPointState',
                data: { id: $(this).attr("data_id"), state: $(this).val() },
                complete: function () {
                    reloadTable();
                }
            });
        });
    });
    function reloadTable() {

    }
</script>