SmartHome/Controllers/API/EndPointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class EndPointsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IEndPointService _endPointService;


        public EndPointsController(ApplicationDbContext context, IEndPointService endPointService)
        {
            _endPointService = endPointService;
            _context = context;
        }


        // GET: api/EndPoints1/5
        [HttpGet("{id}")]
        public async Task<ActionResult<EndPoint>> GetEndPoint(int id, string userId)
        {
            var endPoint = _endPointService.GetEndPointById(id,userId);

            if (endPoint == null)
            {
                return NotFound();
            }

            return endPoint;
        }

        // PUT: api/EndPoints1/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutEndPoint(int id, EndPoint endPoint)
        {
            if (id != endPoint.Id)
            {
                return BadRequest();
            }

            _context.Entry(endPoint).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EndPointExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/EndPoints1
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<EndPoint>> PostEndPoint(EndPoint endPoint)
        {
            _endPointService.CreateEndPoint(endPoint);

            return CreatedAtAction("GetEndPoint", new { id = endPoint.Id }, endPoint);
        }

        // DELETE: api/EndPoints1/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<EndPoint>> DeleteEndPoint(int id, string userId)
        {
            var endPoint = _endPointService.GetEndPointById(id, userId);
            if (endPoint == null)
            {
                return NotFound();
            }

            _endPointService.DeleteEndPoint(id, userId);

            return endPoint;
        }

        private bool EndPointExists(int id)
        {
            return _context.EndPoints.Any(e => e.Id == id);
        }
    }
}

SmartHome/Controllers/HomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Data.Enumerables;
using SmartHome.Models;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers
{
    [Authorize]
    public class HomesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHomeService _homeService;
        private readonly IEndPointService _endPointService;

        public HomesController(ApplicationDbContext context, IHomeService homeService, IEndPointService endPointService)
        {
            _context = context;
            _endPointService = endPointService;
            _homeService = homeService;
        }
        private string GetLoggedInUserId()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return id;
        }
        public PartialViewResult ReloadEndPointsTable(int homeId)
        {
            var model = _context.EndPoints.Where(wh => wh.HomeId == homeId).ToList();
            return PartialView("_EndPointsTable", model);
        }

        //GET: ManageUsersInHome
        public async Task<IActionResult> DeleteUserFromHome(int homeId, string email)
        {
            _homeService.DeleteUserFromHome(homeId, email, GetLoggedInUserId());
            return RedirectToAction("ManageUsersInHome", new { id = homeId });
        }
        //GET: ManageUsersInHome
        public async Task<IActionResult> ManageUsersInHome(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (_homeService.GetHomeById(id.Value, GetLoggedInUserId()) == null)
                return RedirectToAction("Index", "Home", null);
            return View(new ManageUsersViewModel() { HomeId = id.Value, Users = _homeService.GetUsersForHome(id.Value, GetLoggedInUserId()) });
        }

        //GET: AddUserToHome
        public async Task<IActionResult> AddUserToHome(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(new AddUserToHomeViewModel() { HomeId = id.Value, Email = "" });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToHome([Bind("HomeId,Email")] AddUserToHomeViewModel model)
        {
            if (!_homeService.AddUserToHome(model, GetLoggedInUserId()))
            {
                ModelState.AddModelError("Email", "Email not found");
                return View(model);
            }
            return RedirectToAction("ManageUsersInHome", new { id = model.HomeId });
        }

        public async Task<IActionResult> AddEndPointToHome(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(new AddEndPointToHomeViewModel() { HomeId = id.Value, EndPointMAC = "" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEndPointToHome([Bind("HomeId,EndPointMAC")] AddEndPointToHomeViewModel model)
        {
            if (!_endPointService.AddEndPointToHome(model, GetLoggedInUserId()))
            {
                ModelState.AddModelError("EndPointMAC", "EndPoint MAC address not found, endpoint has to be registered first");
                return View(model);
            }
            return RedirectToAction("Details", new { id = model.HomeId });
        }

        // GET: Homes
        public async Task<IActionResult> Index()
        {
            return View(_homeService.GetUserHomes(GetLoggedInUserId()));
        }

        // GET: Homes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = _homeService.GetHomeById(id.Value, GetLoggedInUserId());
            if (home == null)
            {
                return NotFound();
            }

            var model =
                new HomeViewModel()
                {
                    EndPoints = home.EndPoints.Select(sl => new EndPointsViewModel()
                    {
                        Name = sl.Name,
                        Address = sl.Address,
                        Id = sl.Id,
                        Type = sl.Type,
                        State = sl.State
                    }).ToList(),
                    Creator = home.CreatorId,
                    Id = home.Id,
                    IsUserCreator = home.CreatorId == GetLoggedInUserId(),
                    Name = home.Name,                    
                    Actions = new List<SelectListItem>{
                        new SelectListItem { Text = EndPointStateEnum.ON.ToString(), Value = ((int) EndPointStateEnum.ON).ToString()},
                        new SelectListItem { Text = EndPointStateEnum.OFF.ToString(), Value = ((int) EndPointStateEnum.OFF).ToString()},
                        new SelectListItem { Text = EndPointStateEnum.AUTO.ToString(), Value = ((int) EndPointStateEnum.AUTO).ToString()}
                    }
                };
            return View(model);
        }

        [HttpPost]
        public JsonResult ChangeEndPointState(int id, int state)
        {            
            return Json(_endPointService.ChangeEndPointState(id, (EndPointStateEnum)state, GetLoggedInUserId()));
        }

        // GET: Homes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Homes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Home home)
        {
            if (ModelState.IsValid)
            {
                home = _homeService.CreateHome(home, GetLoggedInUserId());

                return RedirectToAction(nameof(Index));
            }
            return View(home);
        }

        // GET: Homes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = _homeService.GetHomeById(id.Value, GetLoggedInUserId());
            if (home == null)
            {
                return NotFound();
            }
            return View(home);
        }

        // POST: Homes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Home home)
        {
            if (id != home.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _homeService.UpdateHome(home, GetLoggedInUserId());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomeExists(home.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(home);
        }

        // GET: Homes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = _homeService.GetHomeById(id.Value, GetLoggedInUserId());
            if (home == null)
            {
                return NotFound();
            }

            return View(home);
        }

        // POST: Homes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _homeService.DeleteHome(id, GetLoggedInUserId());
            return RedirectToAction(nameof(Index));
        }

        private bool HomeExists(int id)
        {
            return _context.Homes.Any(e => e.Id == id);
        }
    }
}

SmartHome/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartHome.Data;
using SmartHome.Data.DbModels;
using SmartHome.Service.Interfaces;

namespace SmartHome.Controllers
{
    public class RulesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IRuleService _ruleService;

        public RulesController(ApplicationDbContext context, IRuleService ruleService)
        {
            _ruleService = ruleService;
            _context = context;
        }

        private string GetLoggedInUserId()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return id;
        }
        // GET: Rules/Create
        public IActionResult Create()
        {
            ViewData["EndPointId"] = new SelectList(_context.EndPoints, "Id", "Id");
            return View();
        }

        // POST: Rules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,RuleType,ValueFrom,ValueTo,TimeFrom,TimeTo,EndPointId")] Rule rule)
        {
            if (ModelState.IsValid)
            {
                _ruleService.CreateRule(rule, GetLoggedInUserId());
                return RedirectToAction("Details","Homes",new { id = rule.EndPoint.HomeId});
            }            
            return View(rule);
        }

        // GET: Rules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rule = _ruleService.GetRuleById(id.Value);
            if (rule == null)
            {
                return NotFound();
            }
            ViewData["EndPointId"] = new SelectList(_context.EndPoints, "Id", "Id", rule.EndPointId);
            return View(rule);
        }

        // POST: Rules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name,RuleType,ValueFrom,ValueTo,TimeFrom,TimeTo,EndPointId")] Rule rule)
        {
            if (id != rule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _ruleService.UpdateRule(rule, GetLoggedInUserId());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RuleExists(rule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ManageRulesForEndPoint","EndPoints", new { id = rule.EndPointId });
            }            
            return View(rule);
        }

        // GET: Rules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rule = _ruleService.GetRuleById(id.Value);
            if (rule == null)
            {
                return NotFound();
            }

            return View(rule);
        }

        // POST: Rules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rule = _ruleService.GetRuleById(id);
            _ruleService.DeleteRule(id, GetLoggedInUserId());
            return RedirectToAction("ManageRulesForEndPoint", "EndPoints", new { id = rule.EndPointId });
        }

        private bool RuleExists(int id)
        {
            return _ruleService.RuleExists(id);
        }
    }
}

SmartHome/Views/EndPoints/AddRuleToEndPoint.cshtml
@model SmartHome.Data.DbModels.Rule

@{
    ViewData["Title"] = "AddRuleToEndPoint";
}

<h1>AddRuleToEndPoint</h1>

<h4>Rule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddRuleToEndPoint">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RuleType" class="control-label"></label>
                <select id="RuleType" asp-for="RuleType"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<SmartHome.Data.Enumerables.RuleTypeEnum>()">
                </select>
                <span asp-validation-for="RuleType" class="text-danger"></span>
            </div>

            <div id="valueType">
                <div class="form-group">
                    <label asp-for="ValueFrom" class="control-label"></label>
                    <input asp-for="ValueFrom" class="form-control" />
                    <span asp-validation-for="ValueFrom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ValueTo" class="control-label"></label>
                    <input asp-for="ValueTo" class="form-control" />
                    <span asp-validation-for="ValueTo" class="text-danger"></span>
                </div>
            </div>
            <div id="timeType" class="hide">
                <div class="form-group">
                    <label asp-for="TimeFrom" class="control-label"></label>
                    <input asp-for="TimeFrom" class="form-control" />
                    <span asp-validation-for="TimeFrom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TimeTo" class="control-label"></label>
                    <input asp-for="TimeTo" class="form-control" />
                    <span asp-validation-for="TimeTo" class="text-danger"></span>
                </div>
            </div>

            <input asp-for="EndPointId" type="hidden"/>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="ManageRulesForEndPoint" asp-controller="EndPoints" asp-route-id="@Model.EndPointId" class="btn btn-light">Back</a>


            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#RuleType").change(function () {
            $(this).find("option:selected").each(function () {
                var optionValue = $(this).attr("value");
                if (optionValue == 1) {
                    $('#valueType').hide();
                    $('#timeType').show();                    
                } else if (optionValue == 2) {
                    $('#valueType').show();
                    $('#timeType').hide();
                } else {
                    $('#valueType').hide();
                    $('#timeType').hide();
                }
            });
        }).change();
    });
</script>

SmartHome/Views/EndPoints/Delete.cshtml
@model SmartHome.Data.DbModels.EndPoint

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EndPoint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Home)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Home.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" asp-controller="Home" class="btn btn-light">Back</a>
    </form>
</div>

SmartHome/Views/EndPoints/Edit.cshtml
@model SmartHome.Data.DbModels.EndPoint

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EndPoint</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select id="Type" asp-for="Type"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<SmartHome.Data.Enumerables.EndPointTypeEnum>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <input type="hidden" class="HomeId" id="HomeId" asp-for="HomeId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Details" asp-route-id="@Model.HomeId" asp-controller="Homes" class="btn btn-light">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartHome/Views/EndPoints/ManageRulesForEndPoint.cshtml
@model EndPointRulesTableViewModel
@{
    ViewData["Title"] = "ManageRulesForEndPoint";
}

<h1>@ViewBag.Title</h1>

<a asp-action="AddRuleToEndPoint" asp-route-id="@Model.EndPointId" class="btn-success btn">New rule</a>

@if (Model.Items.Any())
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Type
                </th>
                <th>
                    From
                </th>
                <th>
                    To
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model.Items)
            {
                <tr>
                    <td>
                        @i.Name
                    </td>
                    <td>
                        @i.RuleType
                    </td>
                    <td>
                        @if (i.RuleType == SmartHome.Data.Enumerables.RuleTypeEnum.TimeBased)
                        {
                            @i.TimeFrom
                        }
                        else
                        {
                            @i.ValueFrom
                        }
                    </td>
                    <td>
                        @if (i.RuleType == SmartHome.Data.Enumerables.RuleTypeEnum.TimeBased)
                        {
                            @i.TimeTo
                        }
                        else
                        {
                            @i.ValueTo
                        }
                    </td>
                    <td>                                                
                        <a asp-action="Edit"  asp-controller="Rules" asp-route-id="@i.Id" class="btn btn-warning">Edit</a>
                        @if (Model.IsUserCreator)
                        {
                            <a asp-action="Delete"  asp-controller="Rules" asp-route-id="@i.Id" class="btn btn-danger">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4>There are no rules for this EndPoint</h4>
}
<a asp-action="Details" asp-controller="Homes" asp-route-id="@Model.HomeId" class="btn btn-light">Back</a>